title: Documentacio
description: Lloc web allotjat a Github amb documentació diversa
theme: just-the-docs

url: https://RafaTeacher.github.io/documentacio

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/RafaTeacher/documentacio
